name: news_clean_architecture
description: "News app with clean architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  get_it: ^7.6.7
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6

flutter:

  uses-material-design: true
  
  fonts:
     - family: Muli
       fonts:
         - asset: assets/fonts/muli/Muli.ttf
         - asset: assets/fonts/muli/Muli-Bold.ttf
           weight: 700
         - asset: assets/fonts/muli/Muli-Light.ttf
